language: node_js
dist: xenial

services:
  - docker

before_install:
  - docker pull amazon/dynamodb-local

node_js:
  - stable

install:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: "jtviegas.js@gmail.com"
  api_key: "bbf516dd-a29f-42ee-b6e7-13742cf435d9"
  on:
    tag: release

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"