language: node_js
dist: xenial
services:
- docker
before_install:
- docker pull amazon/dynamodb-local
node_js:
- stable
install:
- npm install
script:
- npm test
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  cleanup: true
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
