language: node_js
dist: xenial
services:
- docker
before_install:
- docker pull amazon/dynamodb-local
node_js:
- lts/*
install:
- npm install
script:
- npm test
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  cleanup: true
  api_token: "$NPM_TOKEN"
  access: public
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
